### ISSUE TITLE
Getting BigStitcher to work with pyimagej

### ISSUE THREAD

**Issue by alam-shahul** [PreibischLab/BigStitcher#74] opened 2020-06-25 20:35 UTC
Hi! I'm trying to operate BigStitcher in headless mode via pyimagej. I made a [post](https://forum.image.sc/t/running-bigstitcher-plugin-in-pyimagej/39424) on forum.image.sc about my problem.

It works fine when I invoke the macro from the command line, but when I try to do it in pyimagej I get the following error:

```
0
Cannot add scrollbars, it's not a Container but a GenericDialogPlus
```

This seems like a GUI-related error, which makes me think BigStitcher isn't actually running in headless mode when I call it this way. Is there a way to get around this?

**Comment by hoerldavid** [comment] 2020-07-28 17:21
It turns out this was caused by a typo in the input filename.
We should not hang indefinitely in that case, but exit cleanly, I guess.

**Comment by hoerldavid** [comment] 2020-07-29 12:41
Hi @alam-shahul,

There was indeed a bug that would cause the Automatic Loader to run into an infinite loop when an incorrect path is given to it. It should be fixed with https://github.com/PreibischLab/multiview-reconstruction/commit/c194a79aabdb7bf0671c8fcba7e34b3adec5d57f. Now, we show an error message in that case:

![Screenshot 2020-07-29 at 14 34 20](https://user-images.githubusercontent.com/3527592/88801110-7d4b8180-d1a9-11ea-80ab-89b9f57ed948.png)

I made a new release of BigStitcher in Fiji which includes the fix.

Best,
David

**Closed by hoerldavid** 2020-07-29 12:41 UTC

**Comment by alam-shahul** [comment] 2020-07-29 16:09
Oh, great! Thanks for looking into it.
