### ISSUE TITLE
2 angles detected with tiles LZ.1 data 

### ISSUE THREAD

**Issue by schmiedc** [PreibischLab/BigStitcher#1] opened 2017-07-13 12:16 UTC
Hi David and Stephan,

thanks a lot for releasing your software! Great plugin! 

I produce tiled LZ.1 data. This I setup with the small Zeiss application for creating the position lists and then loading this list into the LZ.1 multiview setup.  There are only tiles in there using a meandering tile acquisition (left > right; right > left). I do not specify any angles. However BigStitcher shows me 2 angles. 

I load the .czi with BigStitcher > Define a new Dataset: Zeiss Lightsheet Z.1 Dataset (LOCI Bioformats)
Then I get this: 

![lightsheetz 1properties](https://user-images.githubusercontent.com/10744409/28165300-8fe498b0-67d3-11e7-920a-640f562038df.png)

I guess the problem is with bioformats. I can also post a bug report there but I don't really understand what goes wrong. 

As a quick fix I am able to manipulate the XML in order to circumvent this problem, this clearly shows that there is only one view in the data. Is there anyway to avoid this problem in the first place?

Here is the log from BigStitcher:
[Log.txt](https://github.com/PreibischLab/BigStitcher/files/1145027/Log.txt)

I can send the metadata and the position list of the microscope. 

Cheers,
Christopher

**Comment by hoerldavid** [comment] 2017-07-13 15:58
Hi Christopher,

can you try to load the dataset with BigStitcher > Define a new Dataset: Auto from list of files (LOCI Bioformats) and let me know if it works that way?

I have a feeling that this is caused by a bug (causing all angles with index >=10 to receive rotation=0) I fixed in the Auto-loader but forgot to backport to the CZI-loader. I will look into it.

Cheers,
David

**Comment by schmiedc** [comment] 2017-07-14 10:40
Hi David,

did try "Auto from list of files (LOCI Bioformats)". It did now detect only the tiles and no additional angles. I am resaving to HDF5 now but I think it works! Thanks a lot for the quick response!

What is the idea behind this Auto loading option, or when is this option most useful? I guess for loading .czi its better to use the LZ.1 loader once the bug is fixed. 

Cheers,
Christopher

**Comment by hoerldavid** [comment] 2017-07-19 09:29
(I'll just reopen this as a reminder to myself since I have not yet fixed the bug)

Regarding the standing of the auto loader versus the more specific loaders (CZI, Stacks, ...):

Our plan is to make the "Auto from list of files (LOCI Bioformats)" the default in the future, since it should be able to handle anything that BioFormats can handle (and already has the possibility to add some format-specific code if necessary).

Since this catch-all loader is still experimental and there may be a lot of future bugs, we will keep the old loaders for the time being. But the newest functionality will probably go into the auto loader first and then be backported to the other loaders.

Cheers,
David

**Comment by hoerldavid** [comment] 2017-07-19 14:13
Okay, I just committed the fix -> should become part of the next release.

**Closed by hoerldavid** 2017-07-19 14:13 UTC

**Comment by schmiedc** [comment] 2017-07-19 14:55
Cool! Thanks a lot :) also for the info with the auto loader!
