### ISSUE TITLE
Align poorly linked tiles to nearest neighbors?

### ISSUE THREAD

**Issue by the4thchild** [PreibischLab/BigStitcher#11] opened 2018-01-06 23:12 UTC
Thanks for your excellent stitcher! I had a question about tile alignment with weak links. I noticed that edge (especially corner) tiles that are mostly empty may get fairly misaligned in the z-axis, even after filtering out links will low correlation. Here is a an example after phase correlation, filtering out correlation < 0.4, and global optimization with one round, shown along the y-axis:

![image](https://user-images.githubusercontent.com/1258953/34644828-f725599c-f2f2-11e7-871b-fb908bd99781.png)

I had similar results with the two round optimization option as well. Is there a way to re-filter shifts that went beyond a given displacement? Or to fall back to alignment with the nearest neighbors when correlation is low?

Thanks!

**Comment by StephanPreibisch** [comment] 2018-01-07 09:50
hi, that sounds like it found correlations > 0.4 that were wrong and there is only one link. You also have the option to filter links by maximal displacement from the current location. Did you try that?

**Comment by StephanPreibisch** [comment] 2018-01-07 09:55
We'll also release a new version tomorrow where you can visualize the links afterwards to see if a link still needs to be filtered (see screenshot)
<img width="1361" alt="screen shot 2017-12-29 at 5 34 17 pm" src="https://user-images.githubusercontent.com/1420587/34648430-3894df00-f399-11e7-9f1c-3786ba858fc9.png">

**Comment by the4thchild** [comment] 2018-01-08 03:48
Thanks, and looking forward to the new release. After filtering for < 0.4 and before optimizations, I noticed that one tile remained with avg r = 0.29 (2 links), which was one of the tiles that was misaligned. Should these links have been filtered out, or is this intentional?

Also I found that tiles that have 0 links appear to be placed in their original position even if their neighbors have been shifted a considerable distance. Is there a way to shift tiles with 0 links to follow their surrounding neighbors, rather than falling back to metadata?

I've tried the max displacement option that you mentioned, but I've found that the edge tiles are still sometimes displaced far from their neighbors if the neighbors were shifted in the opposite direction. Is there a way to filter by max displacement from neighbors?

Thanks again!

**Comment by StephanPreibisch** [comment] 2018-01-08 06:59
Hi, it does filter by max displacement to the neighbors. There must be something else going wrong. If a tile has 0 links (what exactly do you mean by that?) they should be moved with their neighbors, except they were not selected for alignment.

Do you have an example for me to play around with to understand your problem?

**Comment by the4thchild** [comment] 2018-01-08 22:29
My image file is rather big (~500GB) so probably difficult to get to you. I've taken some screenshots though to try to explain what I'm seeing.

Here's the stitching explorer after calculating pairwise shifts (using phase correlation) and filtering out R < 0.4, highlighting a tile with 0 links and another tile that shows avg r = 0.29 (all the rest with R < 0.4 were filtered to be > 0.4):
![reg_filt0_04_annot](https://user-images.githubusercontent.com/1258953/34695252-fdb12f38-f47e-11e7-972e-ae62b623a2cc.jpg)

After optimization (one-round with all tiles selected, not just the ones highlighted here), the tile with 0 links stayed in the same position:
![reg_filt0_04_opt_annot](https://user-images.githubusercontent.com/1258953/34695164-a9a6bc1e-f47e-11e7-957e-816f022d9ee1.jpg)

Please let me know if I'm understanding the filtering correctly or if you need more info.

Thanks.

**Comment by StephanPreibisch** [comment] 2018-01-09 07:03
Hi, this is indeed weird. Can you check the log if it tries to calculate something for Tile 17? For the low average correlation, maybe it just doesn't update the table. Can you try to save/load and see if the average r is still 0.29. Finally, please have a look using the link explorer of what happened to those tiles after global optimization (the update will come today, I promise :)

**Comment by the4thchild** [comment] 2018-01-10 06:39
Thanks. I tried saving and reloading the xml file after filtering, but the reloaded file shows values identical to the pre-filtered file, though its file size did change.

Where in the log does it show the calculations for Tile 17? I see the iterations with "Global optimization of 53" but not a tile number. In the "Transformation models" at the end, one row shows "tpId=0 setupId=17: (1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 1, 0), Scaling: 1, 1, 1". I wasn't sure if setupId refers to the tile number as the values start jumping after 38 up to 107 (total tiles is 54).

I didn't see the BigStitcher update yet but will keep an eye out for it and look forward to trying the new link explorer.

**Comment by StephanPreibisch** [comment] 2018-01-10 08:19
Hi, I finally updated the BigStitcher, please check the links to the tiles by pressing 'l' in the BigStitcher (not BigDataViewer) after you ran the global optimization. Everything below 0.4 should be orange. Also, how do these specific links (0.29) look in the LinkExplorer before the global optimization? Can you send me a screenshot of that? And maybe send me the complete log so I can have a look ...

**Comment by the4thchild** [comment] 2018-01-10 23:52
I got the new release (I finally realized you meant "l" as in "L" instead of "i" for the shortcut) -- thanks! I re-ran the shifts/filtering/optimization and copied screenshots here. For some reason all of the links are shown as dashed grey.

Links before global optimization:
![links fresh _filt0 05_z](https://user-images.githubusercontent.com/1258953/34801454-ada978ba-f61d-11e7-86bf-8b06a8ac9936.jpg)

After global optimization (along z and y axes):
![links fresh _filt0 05_opt_z](https://user-images.githubusercontent.com/1258953/34801105-a0bd984a-f61b-11e7-8987-208272b4b832.jpg)

![links fresh _filt0 05_opt_y](https://user-images.githubusercontent.com/1258953/34801108-a6b63d06-f61b-11e7-8d56-45bbb75e7c77.jpg)

By LinkExplorer, do you mean the interactive link explorer table? I have never actually been able to get that one to work (has an empty table and gives a row index out of range error).

Here's the complete log from this stitching session:
[Log12.txt](https://github.com/PreibischLab/BigStitcher/files/1620748/Log12.txt)

Thanks again.

**Comment by StephanPreibisch** [comment] 2018-01-11 08:18
Hi, how do you run the Stitching? Can you post screenshots of that? The fact that all links are gray means that something is wrong.

The Link Explorer pops up automatically when you select "Stitch dataset ...", so that's how we usually run it.

**Comment by the4thchild** [comment] 2018-01-12 02:43
Ah I wonder if that could be the source. I've been running stitching through the "Step-by-step stitching" menu options, with "Calculate Pairwise Shifts > Phase Correlation", then "Verify/Filter Pairwise LInks > "Filter Links by parameters", and finally "Optimize Globally And Apply Shift > Expert Mode". These options appeared to mimic the "Batch Processing" entries in the ImageJ menu, which I've used for scripting the workflow.

I re-ran the stitching through the "Stitch dataset..." wizard and didn't get the Link Explorer exception this time. The visual links worked too. Here's are the screenshots:

![links wizard _z](https://user-images.githubusercontent.com/1258953/34847683-08b3e9bc-f6d1-11e7-94e3-b5f508752a49.jpg)

![links wizard](https://user-images.githubusercontent.com/1258953/34847492-5821774a-f6d0-11e7-8d20-276f822f45e1.jpg)

Interestingly, the results were rather different. This time Tile 17 did have a remaining link and so was shifted. Tile 42 also had 1 link, this time with r of 0.562 (rather than avg r of 0.29). The more strongly misaligned tile in the screenshot was Tile 6, which had a single link (r of 0.472) and previously aligned with the step-by-step workflow. Are different functions used in the "Stitch dataset..." workflow compared to the step-by-step pathway to give these different results?

Increasing the filtering to 0.6 avoids the misalignments. All the tiles with 0 links still are in their exact original position though rather than shifting with neighbors (should they move at least slightly?).
![links wizard _filt0 06_z](https://user-images.githubusercontent.com/1258953/34857024-70dfe7b2-f6fd-11e7-9aea-2e567a154842.jpg)

Also, after showing the links graphically, selecting a row causes all other rows to disappear until they are selected. Is this intentional?
![links_singlerow](https://user-images.githubusercontent.com/1258953/34857021-69a7500c-f6fd-11e7-997e-52c1a4b8437b.jpg)

The graphical link visualizer is definitely helpful.

**Comment by StephanPreibisch** [comment] 2018-01-12 07:49
Hi, good catch, the wizard mode didn't use the new global optimization by default :) The new update does ... try it again now please, everything should be fine. You also mentioned that you didn't find the right key to display the final links, just press F1 and you will get a help screen.

The error in the GUI only happens sometimes when running it directly from Eclipse and not from Fiji, so no idea what is going on there, some bug in the Java GUI? I assume you run it from Eclipse?

I still cannot reproduce your error where links are not removed when not using the "wizard", just works for me.

**Comment by imagejan** [comment] 2018-01-12 13:43
> The error in the GUI only happens sometimes when running it directly from Eclipse and not from Fiji, so no idea what is going on there, some bug in the Java GUI?

I just stumbled upon the same UI issue in a standard Fiji installation (running on Java 1.8.0_144, no eclipse involved):

![image](https://user-images.githubusercontent.com/2033938/34877550-c798c08e-f7a6-11e7-9727-43cabcc9609b.png)

Should we track this in a separate issue?

**Comment by StephanPreibisch** [comment] 2018-01-13 09:55
Yes, please @imagejan  ... if you find a way to reproduce it would be awesome!

**Comment by the4thchild** [comment] 2018-01-13 23:17
Thanks -- I updated BigStitcher to 0.1.6 and re-ran the wizard, and it worked. The previous links that showed up as grey now are orange. Also the tiles with 0 links do shift slightly now.

When I've run step-by-step, my pathway is:
- Select best illuminations (defaults)
- Calculate pairwise shifts > phase correlation (defaults)
- Verify/filter pairwise links > filter links by parameters > filter by link quality with min R of 0.40
- Optimize globally and apply shifts > expert mode > two-rounds (also tried one-round)

Are there differences between the pathway above and what the wizard does? Are there parameters in the wizard that carry over from one step to the next but are lost between steps in the step-by-step pathway? 

I also realized that the exception I was getting at the Link Explorer step (similar to the exception we got when I was demo'ing the stitching with you a few months ago) happens if I had gone through the illumination selection step beforehand. I'm assuming the stitching wizard already includes the illumination selection?

I don't seem to the get the table row visibility GUI error while in step-by-step mode, but only with the wizard. Similarly to @imagejan , I'm running in a standard Fiji install outside of Eclipse (Java 1.8.0_151 on RHEL 7).

Thanks.

**Comment by StephanPreibisch** [comment] 2018-01-14 08:28
Hi Stitching Wizard does not include Illumination Selection ... I have to look at some example data to see what is going wrong there. Obviously the manual link filtering does not work for, but does for me, so not sure why that happens. Maybe it is somehow related to the illumination selection. 

Can you reproduce the GUI problem? I cannot yet, it doesn't happen for me in Fiji, but there I use Java 1.8.0_66 and in Eclipse 1.8.0_144 ... maybe that is the reason somehow. @imagejan which java version do you use?

**Comment by StephanPreibisch** [comment] 2018-01-14 08:39
@the4thchild When running the manual link removal, did you set the checkbox to filter for cross correlation?

**Comment by StephanPreibisch** [comment] 2018-01-14 13:18
@imagejan fixed with commits 32300519f6f6cd83203dbfc4685a03919a029f20 and 67b6437b2087a907515f84e4c5aa8e5acae6a89a

**Comment by the4thchild** [comment] 2018-01-16 06:51
I updated to 0.1.7 with your fixes and can confirm that I don't see the GUI table problem anymore. Thanks!

Yes, I checked the box for cross correlation in the manual link removal. (Is there a way to dim the corresponding text boxes if the checkbox is unchecked?) I tried running the filtering without the illumination selection step just to see if that step might have an impact but get the same filtering issue.

When Illumination Selection isn't applied, how does the stitching treat the illuminators for each tile? Are the two illuminators fused per tile?

**Comment by StephanPreibisch** [comment] 2018-01-17 08:23
Hi @the4thchild, also the illumination selection should be fixed now. So you can do illumination selection first and then run the normal pipeline including the interactive link explorer. Please let us know if it works!

**Comment by StephanPreibisch** [comment] 2018-01-17 08:24
Oh yes, if you do not select an illumination it'll fuse both which is not ideal. But hopefully this is fixed now.

**Comment by the4thchild** [comment] 2018-01-18 03:04
Great, I updated to BigStitcher 0.1.8 and see that the interactive link explorer works now after illumination selection as you mentioned (using "Select Best Illuminations" -> "Stitch dataset ..."). I filtered out < 0.4 and ran optimizations. Afterward I could load the visual links, though they appeared grey again:

![wizard_links_illum_z](https://user-images.githubusercontent.com/1258953/35069558-5eadaf3e-fb8f-11e7-8386-87a70329acd1.jpg)

If I don't select illuminations, the visual links are colored.

When I follow the step-by-step pathway now, I encounter an exception while attempting to run the optimizations in expert mode ("Select Best Illuminations" -> "Pairwise shifts ..." -> "Phase correlation" -> "Verify/filter pairwise links" -> "Follow links by parameters" (similar with interactive explorer) -> "Optimize globally and apply shift ..." -> "Expert mode" -> any mode): 

```
Exception in thread "Thread-59" java.lang.NoSuchMethodError: net.preibisch.mvrecon.fiji.plugin.util.GUIHelper.addScrollBars(Ljava/awt/Container;)V
	at net.preibisch.stitcher.algorithm.globalopt.GlobalOptStitcher.askForFixedViews(GlobalOptStitcher.java:324)
	at net.preibisch.stitcher.algorithm.globalopt.GlobalOptStitcher.processGlobalOptimization(GlobalOptStitcher.java:119)
	at net.preibisch.stitcher.algorithm.globalopt.ExecuteGlobalOpt.run(ExecuteGlobalOpt.java:96)
	at java.lang.Thread.run(Thread.java:748)
```

It works fine when optimizing in simple mode though.

I also went back and compared filtering results using the "Interactive Link Explorer" and the "Filter Links by Parameters" and noticed that there were slight differences, including 1 fewer link in 2 tiles (using min R of 0.4), one of which is the avg r of 0.29 that I'd seen earlier:

```
"Interactive Link Explorer":
0	42, 96	0(id=0)	0(id=0), 1(id=1)	42(id=42)	3505.456, 44912.709, -4088.972	0.506	1
0	52, 106	0(id=0)	0(id=0), 1(id=1)	52(id=52)	1778.343, 46639.823, -4088.972	0.797	4

"Filter Links by Parameters":
0	42, 96	0(id=0)	0(id=0), 1(id=1)	42(id=42)	3505.456, 44912.709, -4088.972	0.29	2
0	52, 106	0(id=0)	0(id=0), 1(id=1)	52(id=52)	1778.343, 46639.823, -4088.972	0.653	5
```

Might this account for links < min R slipping through the 2nd method?

**Comment by StephanPreibisch** [comment] 2018-01-18 07:07
Hi, the bug you found is fixed, that was me yesterday experimenting with some cluster-GUI problems, sorry for that.

**Comment by StephanPreibisch** [comment] 2018-01-18 07:08
Hi @the4thchild, can you post a screenshot of how you run "Filter Links by Parameters"?

**Comment by the4thchild** [comment] 2018-01-18 23:41
Thanks, I updated BigStitcher and can run the optimizations again.

Here are screenshots of running the filtering, first with "Filter Links by Parameters", using default settings except checking the link quality box and changing the min R value:
![dataset_bs0 1 9_stepwise01_manualfilt0 4_popup](https://user-images.githubusercontent.com/1258953/35121247-a1f2336c-fc4f-11e7-9a28-21b9e5d715be.jpg)

and with the "Interactive Link Explorer", where I click on "apply filter":
![dataset_bs0 1 9_stepwise01_interactivefilt0 4_popup](https://user-images.githubusercontent.com/1258953/35121267-af5e383e-fc4f-11e7-81a0-5a45da53a647.jpg)

Please let me know if any of the settings are incorrect to match the filtering between the two methods. I still consistently get the different filtering, and here is the full output for manual vs interactive filtering:
[dataset_bs0.1.9_stepwise01_manualfilt0.4.txt](https://github.com/PreibischLab/BigStitcher/files/1644797/dataset_bs0.1.9_stepwise01_manualfilt0.4.txt)
[dataset_bs0.1.9_stepwise01_interactivefilt0.4.txt](https://github.com/PreibischLab/BigStitcher/files/1644798/dataset_bs0.1.9_stepwise01_interactivefilt0.4.txt)

Also I noticed that pairwise shift output can differ slightly between runs (illumination selection -> pairwise shift -> phase correlation), usually just in slightly different avg R values. Here is the output from 3 different runs, each with a fresh Fiji session and a fresh copy of the original dataset XML file:
[dataset_bs0.1.9_stepwise01_pairwise01.txt](https://github.com/PreibischLab/BigStitcher/files/1644805/dataset_bs0.1.9_stepwise01_pairwise01.txt)
[dataset_bs0.1.9_stepwise01_pairwise02.txt](https://github.com/PreibischLab/BigStitcher/files/1644806/dataset_bs0.1.9_stepwise01_pairwise02.txt)
[dataset_bs0.1.9_stepwise04_pairwise03.txt](https://github.com/PreibischLab/BigStitcher/files/1644807/dataset_bs0.1.9_stepwise04_pairwise03.txt)

I've been double-checking to make sure I'm using the exact same steps each time and have noticed this for the past few days now. Could this be related to state during multiprocessing?

And sorry to bring this up again, but I see the table row GUI error after using the interactive link explorer in the step-by-step pathway:
![dataset_bs0 1 9_stepwise01_interactivefilt0 4_popup_singlerow](https://user-images.githubusercontent.com/1258953/35126887-4ce6c7c4-fc64-11e7-8acc-f237e1a9d84f.jpg)

Not a big deal really as the rows show up so long as I highlight them.

**Comment by StephanPreibisch** [comment] 2018-01-21 11:00
How can I reproduce it @the4thchild @imagejan, I am not able to ...

**Comment by StephanPreibisch** [comment] 2018-01-21 15:30
@the4thchild @imagejan ... should finally be fixed with commit https://github.com/PreibischLab/BigStitcher/commit/1596be3ee238ece05ef9105b98300397655d1c47
Please try again ...

**Closed** 2018-05-12 07:29 UTC
