### ISSUE TITLE
Defining a dataset throws an exception

### ISSUE THREAD

**Issue by haroldGomez** [PreibischLab/BigStitcher#3] opened 2017-08-08 09:45 UTC
Hi guys,

First of, thanks for writing the BigStitcher! I've used often already and I'm quite happy with it. Unfortunately, after updating today, I noticed that defining a new dataset from a CZI file (either through the BigStitcher or the MultiviewReconstruction plugin panels) throws the following exception:
----------
(Fiji Is Just) ImageJ 2.0.0-rc-61/1.51n; Java 1.8.0_66 [64-bit]; Windows Server 2012 R2 6.3; 135MB of 392869MB (<1%)
 
java.lang.NullPointerException
	at spim.fiji.spimdata.SpimDataTools.getFilteredViewDescriptions(SpimDataTools.java:50)
	at spim.fiji.spimdata.SpimDataTools.getFilteredViewDescriptions(SpimDataTools.java:43)
	at spim.fiji.spimdata.explorer.FilteredAndGroupedTableModel.elements(FilteredAndGroupedTableModel.java:155)
	at spim.fiji.spimdata.explorer.FilteredAndGroupedTableModel.<init>(FilteredAndGroupedTableModel.java:147)
	at spim.fiji.spimdata.explorer.ViewSetupExplorerPanel.initComponent(ViewSetupExplorerPanel.java:154)
	at spim.fiji.spimdata.explorer.ViewSetupExplorerPanel.<init>(ViewSetupExplorerPanel.java:118)
	at spim.fiji.spimdata.explorer.ViewSetupExplorerPanel.<init>(ViewSetupExplorerPanel.java:147)
	at spim.fiji.spimdata.explorer.ViewSetupExplorer.<init>(ViewSetupExplorer.java:18)
	at spim.fiji.plugin.Data_Explorer.run(Data_Explorer.java:69)
	at ij.IJ.runUserPlugIn(IJ.java:217)
	at ij.IJ.runPlugIn(IJ.java:181)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:745)
-----------
Any ideas what might have changed in the latest iteration of the code? 

Best,

**Comment by StephanPreibisch** [comment] 2017-08-08 10:08
Hi, could you please let us now how exactly this error occurs (maybe with screenshots)? Thanks so much, Stephan

**Comment by haroldGomez** [comment] 2017-08-08 10:35
Hi Stephan,

Thanks for the prompt reply. This error is happening when I define a new dataset - even with datasets I've stitched before. I've included the screenshots of what I'm doing:


<img width="604" alt="capture2" src="https://user-images.githubusercontent.com/10046683/29068176-f219f3d8-7c35-11e7-8406-8ff5cb735220.PNG">
<img width="661" alt="capture4" src="https://user-images.githubusercontent.com/10046683/29068175-f217b69a-7c35-11e7-988b-6b9bc7037263.PNG">
<img width="914" alt="capture5" src="https://user-images.githubusercontent.com/10046683/29068177-f21c9df4-7c35-11e7-8700-76703faedbb4.PNG">


Best,

**Comment by hoerldavid** [comment] 2017-08-08 11:27
Hi Harold,
are you using the very latest version of BigStitcher?

In short, I think the problem is caused by the GUI wanting to hide missing views, but the `MissingViews` object of CZI datasets is null by default.

In the newest version, you should at least reach the point where the GUI shows (because we will still list missing views), but it will probably crash if you want to do anything with the dataset.

I hope this is a quick fix - I'll do it right away.

**Comment by hoerldavid** [comment] 2017-08-08 12:45
Hi Harold,

I've released a new version of Big_Stitcher (0.9.0-alpha-5) and SPIM_Registration (6.3.1) that should fix your problem.

Let me know if it works, so I can close this.

All the best,
David

**Comment by haroldGomez** [comment] 2017-08-08 13:56
Hi David,

It worked like a charm. Thanks a lot for the quick fix, guys!

Best,

**Closed** 2017-08-08 14:26 UTC
