### ISSUE TITLE
error loading 16-bit grayscale tiles (754 tiles, 3 channels per tile, 3 z-slices per channel)

### ISSUE THREAD

**Issue by bgriffen** [PreibischLab/BigStitcher#16] opened 2018-06-05 21:41 UTC
I have 754 (26*29) tiles in 16-bit, grayscale format.

Tile 557:
Image_XY01_00557_Z001_CH1.tif
Image_XY01_00557_Z001_CH2.tif
Image_XY01_00557_Z001_CH4.tif
Image_XY01_00557_Z002_CH1.tif
Image_XY01_00557_Z002_CH2.tif
Image_XY01_00557_Z002_CH4.tif
Image_XY01_00557_Z003_CH1.tif
Image_XY01_00557_Z003_CH2.tif
Image_XY01_00557_Z003_CH4.tif

Tile 558:
Image_XY01_00558_Z001_CH1.tif
Image_XY01_00558_Z001_CH2.tif
Image_XY01_00558_Z001_CH4.tif
Image_XY01_00558_Z002_CH1.tif
Image_XY01_00558_Z002_CH2.tif
Image_XY01_00558_Z002_CH4.tif
Image_XY01_00558_Z003_CH1.tif
Image_XY01_00558_Z003_CH2.tif
Image_XY01_00558_Z003_CH4.tif

 etc. for 754 tiles.

The formula version would be: `Image_XY01_{iiiii}_Z{zzz}_CH{c}.tif`

iiiii - tilenum
zzz - z-slice num
c - channel num

They are ordered in Snake Format {Right & Down}. I had previously been using the old Grid/Stitch macro in ImageJ which worked fine. What I did do was create a multi-channel image consisting for a given z-stack each channel (*_Multi.tif = *CH1.tif+*CH2.tif+*CH4.tif) then run a stitch for each z-stack. Starting with Z001 I generated TileInfo.registered.txt then fed that into stitching for Z002, Z003, Z004, Z005. I encountered a bug in the code (mainly listed [here](https://list.nih.gov/cgi-bin/wa.exe?A2=ind1610&L=IMAGEJ&F=&S=&P=41767)) and after speaking with Stephan, he suggested BigStitcher which I leads me to my current situation. I can't load the data in. 

Since there appears to be no way to set the z-slice, I just set the formula for that to be a time point. See as follows.

![image_formula](https://user-images.githubusercontent.com/2667869/41004196-e81263d6-68cd-11e8-98f8-ed471ac7b331.png)

In Loading Options, I set it to "Load Raw Data" but then when I proceed, I get `File X could not be opened: java.lang.ArrayIndexOutOfBoundsException Stopping` error.

I've tried a few variations such as just doing a single slice (Z001) and loading the tiles but no luck. Is there something incorrect in my workflow. Is there a formula and setting that allows me to load 16-bit grayscales for each channel at different Z-slices? Thanks in advance and sorry if I missed a memo.

**Comment by hoerldavid** [comment] 2018-06-06 18:37
Hi @bgriffen,

The short answer to your problem is: **we currently do not support z-slices saved to separate files**, we need one file per z-stack. The quickest workaround would probably be to concatenate the single slices and resave them as a stack in ImageJ.

However, this is not the first time this has come up (http://forum.imagej.net/t/bigstitcher-define-dataset-not-working/10403) - so @StephanPreibisch and I just talked and decided to make it a priority to add easier import from single-plane TIFFs. I'll keep this issue open until we have implemented this.

What I'm worried about is that it crashed when you made TimePoints out of the slices or when you tried to load just one slice - this should not happen. I'll have a look if I can reproduce this - could you maybe provide us with the files for two tiles so I can test on your data?

I hope this at least explains the issue - we'll try to add a more convenient import as quickly as possible!

All the best,
David

**Comment by bgriffen** [comment] 2018-06-07 17:43
Thanks! Regarding your concern, it crashed when trying to load any image. I've provided some examples at [the following link](https://drive.google.com/drive/u/1/folders/19ETt4fdci-H2lkHOflP-L-XvJm9KLtW7). It contains The file list I described above, except with 5 slices, not 3. Let me know if you manage to load them correctly. Thanks.

**Comment by hoerldavid** [comment] 2018-07-12 09:20
Hi @bgriffen,

Just wanted to let you know that I implemented reading (and combining) single-plane files (https://github.com/PreibischLab/multiview-reconstruction/tree/singleplane-tiff). We'll include that in one of the next updates in Fiji.

<img width="602" alt="screen shot 2018-07-12 at 11 19 05" src="https://user-images.githubusercontent.com/3527592/42624348-7b51f904-85c5-11e8-931f-23ff02afbbe3.png">

With this, I can open your images. 
**However**, Bio-Formats (which is the basis of our AutoLoader) has some Problems loading your Files. If you just try to open a single file with ```Plugins -> Bio-Formats -> Bio-Formats Importer```, it will actually crash (somehow, it thinks that there are 2 planes or time points and then crashes as it tries to access the second, nonexistent, slice). The new AutoLoader will be able to load the images **if you activate ```Check stack size``` in the loader options**, but I see that more as a lucky coincidence.

I'm not super familiar with the Bio-Formats internals, so I think it would be best if you **file an issue with them, so the problem can be fixed upstream**.

Best,
David

**Comment by hoerldavid** [comment] 2018-08-14 13:01
Hi @bgriffen,

just checking in to let you know that **reading from single-plane TIFFs is now available in the release version in Fiji**.
Since the other problem lies more with Bioformats, I'll close this issue.

Best,
David

**Closed by hoerldavid** 2018-08-14 13:01 UTC

**Comment by bgriffen** [comment] 2018-08-16 17:26
Thank you for making this available. I have been trying to work through the features to get to the same output as what the original Grid Stitching did but it's kind of like Photoshop - so many options and I'm having some difficulty doing what is likely a very simple task. I'll stick at it and let you know if I have any question. Thanks again.
